"""Module implementing the tokenizer and helper functions.

This module converts the valid OMOP concept codes to the embeddings
shipped with the pre-trained model. This allows MOTOR to parse the
codes using embedding that have been pre-computed, and subsequently
be fine-tuned.
"""

import warnings
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

import msgpack
import polars as pl

# The asof join below declines to verify its inputs are ordered once `by` groups are
# given, and says so once per shard. `assign_leaf_tokens` sorts both sides itself --
# the left frame explicitly, the right at load time -- and `_validate_bin_contiguity`
# covers the bins the search runs over. The warning is raised from the Rust core when
# the plan executes, not when it is built, so it surfaces in the caller's collect and
# cannot be scoped to a context manager here.
warnings.filterwarnings(
    "ignore",
    message="Sortedness of columns cannot be checked when 'by' groups provided",
    category=UserWarning,
)


@dataclass(frozen=True)
class TokenTable:
    """Class representing the tokens generated by the tokenizer."""

    code_tokens: dict[str, int]
    numeric_tokens: pl.DataFrame
    text_tokens: pl.DataFrame
    all_parents: Mapping[str, tuple]
    age_mean: float
    age_std: float


def _validate_bin_contiguity(numeric_tokens: pl.DataFrame) -> None:
    """Asserts each code's value bins meet edge to edge, as the asof join assumes.

    The algorithm fails over non-continuous bins.
    The open ends are deliberately not checked. Bins lost to vocab_size are cut
    from the top of a code's range, leaving a shorter but still contiguous run, and
    values above it fall back to the code's own token.

    Args:
        numeric_tokens (pl.DataFrame): The bin lookup, one row per numeric token.

    Raises:
        ValueError: If any code's bins leave a gap, overlap, or repeat.
    """
    faults = (
        numeric_tokens.lazy()
        .sort("code", "val_start")
        .with_columns(next_start=pl.col("val_start").shift(-1).over("code"))
        .filter(
            pl.col("next_start").is_not_null()
            & pl.col("val_end").ne_missing(pl.col("next_start"))
        )
        .collect()
    )
    if faults.is_empty():
        return

    codes = faults["code"].unique(maintain_order=True).to_list()
    first = faults.row(0, named=True)
    raise ValueError(
        f"{len(codes)} code(s) in the vocabulary hold value bins that do not meet "
        f"edge to edge: {codes[:5]}. {first['code']} closes a bin at "
        f"{first['val_end']} and opens the next at {first['next_start']}; leaf "
        f"assignment reads val_start alone, so every value between the two would be "
        f"tokenised as the bin below it."
    )


def load_token_table(dictionary_path: Path, *, vocab_size: int) -> TokenTable:
    """Extracts the MOTOR vocabulary with each code's index in the rollup.

    Forks the load_token_table helper under coverage.py as that version
    drops the indices. This function returns a mapping of codes to their
    indices in the shipped vocabulary.

    Args:
        dictionary_path (Path): Path to the MOTOR vocabulary.
        vocab_size (int): Number of tokens defined in the vocabulary.

    Returns:
        TokenTable: A custom container holding the mapping of code to
            row in the vocabulary, and useful summary statistics for age

    Raises:
        ValueError: If the vocab_size is negative, or if the length of the
            rollup is less than the vocabulary size.
    """
    if vocab_size <= 0:
        raise ValueError(f"The minimum vocabulary size is 1. Received {vocab_size}.")
    with open(dictionary_path, "rb") as f:
        dictionary = msgpack.load(f, use_list=False, strict_map_key=False)
    rollup = dictionary["ontology_rollup"]
    if len(rollup) < vocab_size:
        raise ValueError(
            f"vocab_size {vocab_size} exceeds the {len(rollup)} entries in "
            f"{dictionary_path}. The tokens would not line up with the model's "
            f"embedding table; check the vocab_size the model config declares."
        )
    vocab = rollup[:vocab_size]
    all_parents = dictionary["all_parents"]
    age_mean = dictionary["age_stats"]["mean"]
    age_std = dictionary["age_stats"]["std"]

    code_tokens: dict[str, int] = {}
    numeric_code: list[str] = []
    val_start: list[float] = []
    val_end: list[float] = []
    numeric_indices: list[int] = []
    text_codes: list[str] = []
    text_strings: list[str] = []
    text_indices: list[int] = []

    for index, vocab_entry in enumerate(vocab):
        code = vocab_entry["code_string"]
        text_string = vocab_entry["text_string"]
        match vocab_entry["type"]:
            case 0:
                code_tokens[code] = index
            case 1:
                numeric_code.append(code)
                val_start.append(vocab_entry["val_start"])
                val_end.append(vocab_entry["val_end"])
                numeric_indices.append(index)
            case 2:
                text_codes.append(code)
                text_strings.append(text_string)
                text_indices.append(index)
            case _:
                continue

    # the asof join in leaf assignment binary-searches this frame within each code,
    # so it is ordered here rather than trusted to arrive ordered
    numeric_tokens = pl.DataFrame(
        data={
            "code": pl.Series(numeric_code, dtype=pl.String),
            "val_start": pl.Series(val_start, dtype=pl.Float64),
            "val_end": pl.Series(val_end, dtype=pl.Float64),
            "numeric_indices": pl.Series(numeric_indices, dtype=pl.UInt32),
        }
    ).sort("code", "val_start")
    _validate_bin_contiguity(numeric_tokens)

    return TokenTable(
        code_tokens=code_tokens,
        numeric_tokens=numeric_tokens,
        text_tokens=pl.DataFrame(
            data={
                "code": pl.Series(text_codes, dtype=pl.String),
                "text_string": pl.Series(text_strings, dtype=pl.String),
                "text_indices": pl.Series(text_indices, dtype=pl.UInt32),
            }
        ),
        all_parents=all_parents,
        age_mean=age_mean,
        age_std=age_std,
    )


def assign_leaf_tokens(events: pl.LazyFrame, table: TokenTable) -> pl.LazyFrame:
    """Assigns a vocabulary index to each event depending on code.

    The codes have been standardized into OMOP concepts but they still
    need the embedding learned from pretraining. This function assigns
    the index of the code in the vocabulary so that the embedding is
    recoverable.

    The bin wins over the recorded text, which wins over the bare code, because
    that is the order of specificity. femr instead switches on the event's value
    type and never falls back, so we are **deliberately more generous in two
    places**: an event carrying a numeric value on a code holding no bins takes
    that code's token here and no token at all in femr, and a value femr's linear
    bin scan would miss lands in the bin below it here. Both hand the model a
    token in a context pretraining never produced. Kept on purpose pending the
    first fine-tuning trials; revisit if the results look off.

    Args:
        events (pl.LazyFrame): MEDS events carrying `code`, `numeric_value` and
            `text_value`.
        table (TokenTable): The loaded vocabulary.

    Returns:
        pl.LazyFrame: The events in their original order, with an `index` column
            naming each one's leaf token. Events the vocabulary cannot name are
            dropped.
    """
    numeric_tokens = table.numeric_tokens.lazy()
    text_tokens = table.text_tokens.lazy()

    events_with_leaves = (
        events.with_row_index("row_index")
        .sort(["code", "numeric_value"])
        .join_asof(
            numeric_tokens,
            by="code",
            left_on="numeric_value",
            right_on="val_start",
            strategy="backward",
        )
        .join(
            text_tokens,
            left_on=["code", "text_value"],
            right_on=["code", "text_string"],
            how="left",
        )
        .with_columns(
            code_indices=pl.col("code").replace_strict(
                table.code_tokens, default=None, return_dtype=pl.UInt32
            )
        )
        .with_columns(
            index=pl.coalesce("numeric_indices", "text_indices", "code_indices")
        )
        .drop_nulls("index")
    )

    return events_with_leaves.sort("row_index").drop(
        [
            "row_index",
            "val_start",
            "val_end",
            "numeric_indices",
            "text_indices",
            "code_indices",
        ]
    )


def build_ancestor_expansion(table: TokenTable) -> pl.LazyFrame:
    """Constructs an ancestor expansion table based on the vocabulary.

    In MOTOR an event's vector is the sum of several embedding rows, and which
    rows depends on the kind of token it resolved to. Because that set is a
    property of the token and not of the event, it is precomputed here once and
    joined per batch.

    A bare code contributes its own row plus one for every ancestor the
    vocabulary holds. A value bin or a recorded text value contributes its
    own row only.

    Ancestors outside the vocabulary are dropped rather than climbed.

    Args:
        table (TokenTable): Custom object holding the representation of
            each token in the vocabulary.

    Returns:
        pl.LazyFrame: One row per (leaf token, contributing token) pair, columns
            index and token, sorted by both so the artifact is reproducible.
            index matches the column assign_leaf_tokens emits.
    """
    leaves: list[int] = []
    tokens: list[int] = []

    for code, index in table.code_tokens.items():
        # all_parents carries the code itself, but not every code is in it
        chain = {
            table.code_tokens[ancestor]
            for ancestor in table.all_parents.get(code, ())
            if ancestor in table.code_tokens
        }
        chain.add(index)
        leaves.extend([index] * len(chain))
        tokens.extend(sorted(chain))

    valued = [
        *table.numeric_tokens["numeric_indices"].to_list(),
        *table.text_tokens["text_indices"].to_list(),
    ]
    leaves.extend(valued)
    tokens.extend(valued)

    return (
        pl.DataFrame(
            {
                "index": pl.Series(leaves, dtype=pl.UInt32),
                "token": pl.Series(tokens, dtype=pl.UInt32),
            }
        )
        .lazy()
        .sort("index", "token")
    )


def expand_leaf_tokens(events: pl.LazyFrame, expansion: pl.LazyFrame) -> pl.LazyFrame:
    """Fans each event out into the embedding rows that make up its vector.

    Args:
        events (pl.LazyFrame): Events carrying the index column that
            assign_leaf_tokens emits, in sequence order.
        expansion (pl.LazyFrame): The table build_ancestor_expansion returns.

    Returns:
        pl.LazyFrame: One row per pair, columns token then position so the
            collected frame is already in the (read, write) column order
            HierarchicalEmbedding, sorted by position.
    """
    return (
        events.with_row_index("position")
        .join(expansion, on="index", how="inner")
        .sort("position", "token")
        .select("token", "position")
    )
