"""Module implementing the tokenizer and helper functions."""

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

import msgpack
import polars as pl


@dataclass(frozen=True)
class TokenTable:
    """Class representing the tokens generated by the tokenizer."""

    code_tokens: dict[str, int]
    numeric_tokens: pl.DataFrame
    text_tokens: dict[tuple[str, str], int]
    all_parents: Mapping[str, tuple]
    age_mean: float
    age_std: float


def load_token_table(dictionary_path: Path, *, vocab_size: int) -> TokenTable:
    """Extracts the MOTOR vocabulary with each code's index in the rollup.

    Forks the load_token_table helper under coverage.py as that version
    drops the indices. This function returns a mapping of codes to their
    indices in the shipped vocabulary.

    Args:
        dictionary_path (Path): Path to the MOTOR vocabulary.
        vocab_size (int): Number of tokens defined in the vocabulary.

    Returns:
        TokenTable: A custom container holding the mapping of code to
            row in the vocabulary, and useful summary statistics for age

    Raises:
        ValueError: If the vocab_size is negative, or if the length of the
            rollup is less than the vocabulary size.
    """
    if vocab_size <= 0:
        raise ValueError(f"The minimum vocabulary size is 1. Received {vocab_size}.")
    with open(dictionary_path, "rb") as f:
        dictionary = msgpack.load(f, use_list=False, strict_map_key=False)
    rollup = dictionary["ontology_rollup"]
    if len(rollup) < vocab_size:
        raise ValueError(
            f"vocab_size {vocab_size} exceeds the {len(rollup)} entries in "
            f"{dictionary_path}. The tokens would not line up with the model's "
            f"embedding table; check the vocab_size the model config declares."
        )
    vocab = rollup[:vocab_size]
    all_parents = dictionary["all_parents"]
    age_mean = dictionary["age_stats"]["mean"]
    age_std = dictionary["age_stats"]["std"]

    code_tokens: dict[str, int] = {}
    numeric_code: list[str] = []
    val_start: list[float] = []
    val_end: list[float] = []
    numeric_indices: list[int] = []
    text_tokens: dict[tuple[str, str], int] = {}

    for index, vocab_entry in enumerate(vocab):
        code = vocab_entry["code_string"]
        text_string = vocab_entry["text_string"]
        match vocab_entry["type"]:
            case 0:
                code_tokens[code] = index
            case 1:
                numeric_code.append(code)
                val_start.append(vocab_entry["val_start"])
                val_end.append(vocab_entry["val_end"])
                numeric_indices.append(index)
            case 2:
                text_tokens[(code, text_string)] = index
            case _:
                continue

    return TokenTable(
        code_tokens=code_tokens,
        numeric_tokens=pl.DataFrame(
            data={
                "code": pl.Series(numeric_code, dtype=pl.String),
                "val_start": pl.Series(val_start, dtype=pl.Float64),
                "val_end": pl.Series(val_end, dtype=pl.Float64),
                "indices": pl.Series(numeric_indices, dtype=pl.UInt32),
            }
        ),
        text_tokens=text_tokens,
        all_parents=all_parents,
        age_mean=age_mean,
        age_std=age_std,
    )
